version: "3.9"

services:
  data-catalog:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: data-catalog
    depends_on:
      elasticsearch:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - .env
    ports:
      - "8000:8000"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.3
    container_name: es
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    # No ports exposed to localhost
    volumes:
      - ./data/esdata:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://elasticsearch:9200/_cluster/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 30

  redis:
    image: redis:7.0
    container_name: redis
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./data/redis:/data
